package com.mambu.bancomambu.enum

enum class LanguageEnum {

    ENGLISH, PORTUGESE, SPANISH, RUSSIAN, FRENCH, GEORGIAN, CHINESE, INDONESIAN, ROMANIAN, BURMESE, GERMAN, PORTUGUESE_BRAZIL, VIETNAMESE, ITALIAN, PHRASE
}